name: build application
on:
  push:
    branches:
      - 'master'
#   release:
#     types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to github container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        run: |
          docker build -t ghcr.io/buraito-kun/devops-assignment:latest backend-apps/
          docker push ghcr.io/buraito-kun/devops-assignment:latest
