name: build application
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to github container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        run: |
          docker build -t ghcr.io/buraito-kun/devops-assignment:${{ github.ref_name }} -t ghcr.io/buraito-kun/devops-assignment:latest backend-apps/
          docker push ghcr.io/buraito-kun/devops-assignment:${{ github.ref_name }}
          docker push ghcr.io/buraito-kun/devops-assignment:latest
  deployment:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Pull image
        run: docker pull ghcr.io/buraito-kun/devops-assignment:${{ github.ref_name }}
      - name: Deploy using terraform
        run: |
          cd infra-code
          terraform init
          kubectl delete deployment backend-apps --ignore-not-found=true
          terraform apply -auto-approve -var 'image_version=${{ github.ref_name }}'
